@startuml
left to right direction

:Patron:
:Debtor:
:Librarian:

:Debtor:<|..:Patron:: extends

rectangle Library {
(Authorization)
(Returning a book)
(Book borrowing)
(Review of borrowed books)
(Get in queue for a book)
(View queue)
(Receiving notifications)

(Search for a book)

(Registration of new patrons)
(User management)
(Adding new books)
(Catalog management)
(View all borrowings)
(View all debtors)
(Process book reservations)

:Debtor:-->(Returning a book)

:Patron:-->(Authorization)
:Patron:-->(Receiving notifications)
:Patron:-->(Search for a book)

:Librarian:-->(Search for a book)
:Librarian:-->(Registration of new patrons)
:Librarian:-->(User management)
:Librarian:-->(Adding new books)
:Librarian:-->(Catalog management)
:Librarian:-->(View all borrowings)
:Librarian:-->(View all debtors)
:Librarian:-->(Process book reservations)


(Book borrowing)..>(Authorization) :use
(Get in queue for a book)..>(Authorization): use

(Review of borrowed books)..>(Book borrowing): use
(Returning a book)..>(Book borrowing): include


(Book borrowing)..>(Adding new books): include

(Search for a book)..>(Adding new books): include

(Process book reservations)..>(Book borrowing): use
(Process book reservations)..>(Review of borrowed books): use
(Process book reservations)..>(Returning a book): use
(View queue)..>(Get in queue for a book): use
(Get in queue for a book)..>(Adding new books): extends
(View all borrowings)..>(Adding new books): use
(View all borrowings)..>(View all debtors): include
(Adding new books)..>(Catalog management): extends


}
@enduml
