@startuml

skinparam linetype polyline
left to right direction

frame "External Systems" as EXT {
  node "<<external>>\nEmail Gateway" as MsgGateway
}

frame "Library System (System Boundary)" {
  component "Client UI / Web" as UI
  interface I_UI
  UI --> I_UI

  component "API Gateway / Backend" as APIGW
  interface I_API
  I_UI --> I_API
  APIGW <-- I_API

  component "Catalog Service" as Catalog
  interface I_Catalog
  APIGW --> I_Catalog
  Catalog <-- I_Catalog

  component "Inventory Service" as Inventory
  interface I_Inventory
  APIGW --> I_Inventory
  Inventory <-- I_Inventory

  component "Circulation Service" as Circulation
  interface I_Circulation
  APIGW --> I_Circulation
  Circulation <-- I_Circulation

  component "User Service" as UserService
  interface I_User
  APIGW --> I_User
  UserService <-- I_User

  component "Notification Service" as Notify
  interface I_Notify
  APIGW --> I_Notify
  Notify <-- I_Notify
  
  component "Catalog Repository" as CatalogRepo
  interface I_CatalogRepo
  Catalog -> I_CatalogRepo
  CatalogRepo <- I_CatalogRepo
  
  component "Inventory Repository" as InventoryRepo
  interface I_InventoryRepo
  Inventory -> I_InventoryRepo
  InventoryRepo <- I_InventoryRepo
  
  component "Circulation Repository" as CirculationRepo
  interface I_CirculationRepo
  Circulation -> I_CirculationRepo
  CirculationRepo <- I_CirculationRepo
  
  component "User Repository" as UserRepo
  interface I_UserRepo
  UserService -> I_UserRepo
  UserRepo <- I_UserRepo
  
  component "Notification Repository" as NotifyRepo
  interface I_NotifyRepo
  Notify -> I_NotifyRepo
  NotifyRepo <- I_NotifyRepo

  database "Library Database:\nbook, author, genre,\nauthor_book, book_genres,\nbook_copy, checkout, waitlist,\nwishlist, patron, notification" as DB
  CatalogRepo -> DB
  InventoryRepo -> DB
  CirculationRepo -> DB
  UserRepo -> DB
  NotifyRepo -> DB

  component "Auth Service" as Auth
  interface I_Auth
  APIGW --> I_Auth
  Auth --> I_UserRepo
  Auth <-- I_Auth

  Notify --> MsgGateway
}


legend right
  Catalog Service -> book, author, genre, author_book, book_genres
  Inventory Service -> book_copy
  Circulation Service -> checkout, waitlist, wishlist
  User Service -> patron
  Notification Service -> notification
endlegend

@enduml